// Real clubs from target leagues with realistic squad data
// This data is used when API-Football key is not configured
// It mirrors the structure returned by API-Football's /v3/players/squads endpoint

export const SAMPLE_CLUBS = [
  {
    club_id: 79,
    name: "FC Nantes",
    league: "Ligue 1",
    country: "France",
    logo: "https://media.api-sports.io/football/teams/79.png",
    squad: [
      { name: "Alban Lafont", age: 25, position: "Goalkeeper" },
      { name: "Rémy Descamps", age: 28, position: "Goalkeeper" },
      {
        name: "Jean-Charles Castelletto",
        age: 29,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Nicolas Pallois",
        age: 37,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Fabien Centonze",
        age: 28,
        position: "Defender",
        sub_position: "Right-Back",
      },
      {
        name: "Quentin Merlin",
        age: 23,
        position: "Defender",
        sub_position: "Left-Back",
      },
      {
        name: "Dennis Appiah",
        age: 33,
        position: "Defender",
        sub_position: "Right-Back",
        injured: true,
        injury_type: "ACL",
        return_date: "2026-06",
      },
      {
        name: "Pedro Chirivella",
        age: 27,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Moussa Sissoko",
        age: 35,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Florent Mollet",
        age: 31,
        position: "Midfielder",
        sub_position: "Attacking Midfield",
      },
      {
        name: "Moses Simon",
        age: 29,
        position: "Attacker",
        sub_position: "Left Winger",
      },
      {
        name: "Mostafa Mohamed",
        age: 26,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
      {
        name: "Ludovic Blas",
        age: 27,
        position: "Attacker",
        sub_position: "Left Winger",
      },
      {
        name: "Ignatius Ganago",
        age: 25,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
    ],
  },
  {
    club_id: 116,
    name: "RC Lens",
    league: "Ligue 1",
    country: "France",
    logo: "https://media.api-sports.io/football/teams/116.png",
    squad: [
      { name: "Brice Samba", age: 30, position: "Goalkeeper" },
      { name: "Hervé Koffi", age: 27, position: "Goalkeeper" },
      {
        name: "Kevin Danso",
        age: 26,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Facundo Medina",
        age: 25,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Jonathan Gradit",
        age: 34,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Deiver Machado",
        age: 30,
        position: "Defender",
        sub_position: "Left-Back",
      },
      {
        name: "Jimmy Cabot",
        age: 30,
        position: "Defender",
        sub_position: "Right-Back",
      },
      {
        name: "Salis Abdul Samed",
        age: 24,
        position: "Midfielder",
        sub_position: "Defensive Midfield",
      },
      {
        name: "Angelo Fulgini",
        age: 28,
        position: "Midfielder",
        sub_position: "Attacking Midfield",
      },
      {
        name: "Adrien Thomasson",
        age: 30,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Elye Wahi",
        age: 22,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
      {
        name: "Florian Sotoca",
        age: 33,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
      {
        name: "Rémy Labeau Lascary",
        age: 21,
        position: "Attacker",
        sub_position: "Right Winger",
      },
    ],
  },
  {
    club_id: 1032,
    name: "Saint-Étienne",
    league: "Ligue 1",
    country: "France",
    logo: "https://media.api-sports.io/football/teams/1032.png",
    squad: [
      { name: "Gautier Larsonneur", age: 27, position: "Goalkeeper" },
      { name: "Etienne Green", age: 24, position: "Goalkeeper" },
      {
        name: "Dylan Batubinsika",
        age: 28,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Yunis Abdelhamid",
        age: 38,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Léo Pétrot",
        age: 26,
        position: "Defender",
        sub_position: "Left-Back",
      },
      {
        name: "Yvann Maçon",
        age: 26,
        position: "Defender",
        sub_position: "Right-Back",
      },
      {
        name: "Pierre Ekwah",
        age: 22,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Lamine Fomba",
        age: 26,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Zuriko Davitashvili",
        age: 24,
        position: "Attacker",
        sub_position: "Right Winger",
      },
      {
        name: "Ibrahim Sissoko",
        age: 27,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
      {
        name: "Irvin Cardona",
        age: 27,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
    ],
  },
  {
    club_id: 554,
    name: "RSC Anderlecht",
    league: "Pro League",
    country: "Belgium",
    logo: "https://media.api-sports.io/football/teams/554.png",
    squad: [
      { name: "Kasper Schmeichel", age: 39, position: "Goalkeeper" },
      { name: "Colin Coosemans", age: 28, position: "Goalkeeper" },
      {
        name: "Zanka",
        age: 34,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Jan Vertonghen",
        age: 38,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Moussa N'Diaye",
        age: 22,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Ludwig Augustinsson",
        age: 30,
        position: "Defender",
        sub_position: "Left-Back",
      },
      {
        name: "Amir Murillo",
        age: 28,
        position: "Defender",
        sub_position: "Right-Back",
      },
      {
        name: "Anders Dreyer",
        age: 26,
        position: "Attacker",
        sub_position: "Right Winger",
      },
      {
        name: "Francis Amuzu",
        age: 25,
        position: "Attacker",
        sub_position: "Left Winger",
      },
      {
        name: "Yari Verschaeren",
        age: 24,
        position: "Midfielder",
        sub_position: "Attacking Midfield",
      },
      {
        name: "Majeed Ashimeru",
        age: 27,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Kasper Dolberg",
        age: 27,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
    ],
  },
  {
    club_id: 569,
    name: "Club Brugge",
    league: "Pro League",
    country: "Belgium",
    logo: "https://media.api-sports.io/football/teams/569.png",
    squad: [
      { name: "Simon Mignolet", age: 36, position: "Goalkeeper" },
      { name: "Senne Lammens", age: 22, position: "Goalkeeper" },
      {
        name: "Brandon Mechele",
        age: 31,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Abakar Sylla",
        age: 21,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Bjorn Meijer",
        age: 23,
        position: "Defender",
        sub_position: "Left-Back",
      },
      {
        name: "Kyriani Sabbe",
        age: 22,
        position: "Defender",
        sub_position: "Right-Back",
      },
      {
        name: "Hans Vanaken",
        age: 32,
        position: "Midfielder",
        sub_position: "Attacking Midfield",
      },
      {
        name: "Casper Nielsen",
        age: 28,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Hugo Vetlesen",
        age: 24,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Ferran Jutglà",
        age: 25,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
      {
        name: "Chemsdine Talbi",
        age: 21,
        position: "Attacker",
        sub_position: "Right Winger",
      },
      {
        name: "Andreas Skov Olsen",
        age: 25,
        position: "Attacker",
        sub_position: "Right Winger",
      },
    ],
  },
  {
    club_id: 538,
    name: "KRC Genk",
    league: "Pro League",
    country: "Belgium",
    logo: "https://media.api-sports.io/football/teams/538.png",
    squad: [
      { name: "Hendrik Van Crombrugge", age: 31, position: "Goalkeeper" },
      { name: "Maarten Vandevoordt", age: 22, position: "Goalkeeper" },
      {
        name: "Mark McKenzie",
        age: 25,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Mujaid Sadick",
        age: 25,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Carlos Cuesta",
        age: 25,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Gerardo Arteaga",
        age: 26,
        position: "Defender",
        sub_position: "Left-Back",
      },
      {
        name: "Bryan Heynen",
        age: 27,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Patrik Hrošovský",
        age: 32,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Bilal El Khannouss",
        age: 20,
        position: "Midfielder",
        sub_position: "Attacking Midfield",
      },
      {
        name: "Tolu Arokodare",
        age: 24,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
      {
        name: "Luca Oyen",
        age: 21,
        position: "Attacker",
        sub_position: "Left Winger",
      },
    ],
  },
  {
    club_id: 620,
    name: "FC Basel",
    league: "Super League",
    country: "Switzerland",
    logo: "https://media.api-sports.io/football/teams/620.png",
    squad: [
      { name: "Marwin Hitz", age: 37, position: "Goalkeeper" },
      { name: "Gauthier Descloux", age: 28, position: "Goalkeeper" },
      {
        name: "Andy Pelmard",
        age: 24,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Arnau Comas",
        age: 25,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Riccardo Calafiori",
        age: 22,
        position: "Defender",
        sub_position: "Left-Back",
      },
      {
        name: "Tomas Tavares",
        age: 22,
        position: "Defender",
        sub_position: "Right-Back",
      },
      {
        name: "Fabian Frei",
        age: 36,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Taulant Xhaka",
        age: 33,
        position: "Midfielder",
        sub_position: "Defensive Midfield",
      },
      {
        name: "Darian Males",
        age: 23,
        position: "Attacker",
        sub_position: "Right Winger",
      },
      {
        name: "Thierno Barry",
        age: 21,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
      {
        name: "Kevin Carlos",
        age: 23,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
    ],
  },
  {
    club_id: 621,
    name: "Young Boys",
    league: "Super League",
    country: "Switzerland",
    logo: "https://media.api-sports.io/football/teams/621.png",
    squad: [
      { name: "David von Ballmoos", age: 29, position: "Goalkeeper" },
      { name: "Anthony Racioppi", age: 25, position: "Goalkeeper" },
      {
        name: "Mohamed Ali Camara",
        age: 27,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Loris Benito",
        age: 32,
        position: "Defender",
        sub_position: "Left-Back",
      },
      {
        name: "Ulisses Garcia",
        age: 30,
        position: "Defender",
        sub_position: "Left-Back",
      },
      {
        name: "Lewin Blum",
        age: 22,
        position: "Defender",
        sub_position: "Right-Back",
      },
      {
        name: "Sandro Lauper",
        age: 27,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Filip Ugrinic",
        age: 24,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Meschack Elia",
        age: 27,
        position: "Attacker",
        sub_position: "Left Winger",
      },
      {
        name: "Cedric Itten",
        age: 27,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
    ],
  },
  {
    club_id: 336,
    name: "Lech Poznań",
    league: "Ekstraklasa",
    country: "Poland",
    logo: "https://media.api-sports.io/football/teams/336.png",
    squad: [
      { name: "Filip Bednarek", age: 27, position: "Goalkeeper" },
      { name: "Krzysztof Kotorowski", age: 23, position: "Goalkeeper" },
      {
        name: "Bartosz Salamon",
        age: 33,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Antonio Milić",
        age: 28,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Joel Pereira",
        age: 25,
        position: "Defender",
        sub_position: "Left-Back",
      },
      {
        name: "Pedro Rebocho",
        age: 28,
        position: "Defender",
        sub_position: "Left-Back",
      },
      {
        name: "Afonso Sousa",
        age: 24,
        position: "Midfielder",
        sub_position: "Attacking Midfield",
      },
      {
        name: "Radosław Murawski",
        age: 28,
        position: "Midfielder",
        sub_position: "Defensive Midfield",
      },
      {
        name: "Ali Gholizadeh",
        age: 28,
        position: "Attacker",
        sub_position: "Right Winger",
      },
      {
        name: "Mikael Ishak",
        age: 33,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
      {
        name: "Filip Szymczak",
        age: 21,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
    ],
  },
  {
    club_id: 338,
    name: "Legia Warsaw",
    league: "Ekstraklasa",
    country: "Poland",
    logo: "https://media.api-sports.io/football/teams/338.png",
    squad: [
      { name: "Kacper Tobiasz", age: 22, position: "Goalkeeper" },
      { name: "Marcel Mendes-Dudziński", age: 20, position: "Goalkeeper" },
      {
        name: "Artur Jędrzejczyk",
        age: 36,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Steve Kapuadi",
        age: 24,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Rafał Augustyniak",
        age: 31,
        position: "Midfielder",
        sub_position: "Defensive Midfield",
      },
      {
        name: "Bartosz Slisz",
        age: 25,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Josué",
        age: 31,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Ernest Muçi",
        age: 23,
        position: "Attacker",
        sub_position: "Left Winger",
      },
      {
        name: "Blaz Kramer",
        age: 28,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
      {
        name: "Marc Gual",
        age: 28,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
    ],
  },
  {
    club_id: 194,
    name: "FC Twente",
    league: "Eredivisie",
    country: "Netherlands",
    logo: "https://media.api-sports.io/football/teams/194.png",
    squad: [
      { name: "Lars Unnerstall", age: 33, position: "Goalkeeper" },
      { name: "Przemyslaw Tyton", age: 37, position: "Goalkeeper" },
      {
        name: "Mees Hilgers",
        age: 23,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Robin Pröpper",
        age: 30,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Gijs Smal",
        age: 25,
        position: "Defender",
        sub_position: "Left-Back",
      },
      {
        name: "Alec Van Hoorenbeeck",
        age: 22,
        position: "Defender",
        sub_position: "Right-Back",
      },
      {
        name: "Ricky van Wolfswinkel",
        age: 35,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
      {
        name: "Sem Steijn",
        age: 22,
        position: "Midfielder",
        sub_position: "Attacking Midfield",
      },
      {
        name: "Michal Sadílek",
        age: 25,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Michel Vlap",
        age: 27,
        position: "Attacker",
        sub_position: "Attacking Midfield",
      },
      {
        name: "Daan Rots",
        age: 22,
        position: "Attacker",
        sub_position: "Right Winger",
      },
    ],
  },
  {
    club_id: 197,
    name: "FC Utrecht",
    league: "Eredivisie",
    country: "Netherlands",
    logo: "https://media.api-sports.io/football/teams/197.png",
    squad: [
      { name: "Vasilis Barkas", age: 30, position: "Goalkeeper" },
      { name: "Thijmen Nijhuis", age: 22, position: "Goalkeeper" },
      {
        name: "Mike van der Hoorn",
        age: 33,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Willem Janssen",
        age: 35,
        position: "Defender",
        sub_position: "Centre-Back",
      },
      {
        name: "Mark van der Maarel",
        age: 34,
        position: "Defender",
        sub_position: "Right-Back",
      },
      {
        name: "Django Warmerdam",
        age: 26,
        position: "Defender",
        sub_position: "Left-Back",
      },
      {
        name: "Sander van de Streek",
        age: 32,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "Quinten Timber",
        age: 25,
        position: "Midfielder",
        sub_position: "Central Midfield",
      },
      {
        name: "David Min",
        age: 22,
        position: "Attacker",
        sub_position: "Left Winger",
      },
      {
        name: "Can Bozdogan",
        age: 23,
        position: "Midfielder",
        sub_position: "Attacking Midfield",
      },
      {
        name: "Adrian Dalmau",
        age: 28,
        position: "Attacker",
        sub_position: "Centre-Forward",
      },
    ],
  },
];

// Target leagues and their API-Football IDs
export const TARGET_LEAGUES = [
  { id: 218, name: "Bundesliga", country: "Austria", flag: "AT" },
  { id: 106, name: "Ekstraklasa", country: "Poland", flag: "PL" },
  { id: 94, name: "Primeira Liga", country: "Portugal", flag: "PT" },
  { id: 88, name: "Eredivisie", country: "Netherlands", flag: "NL" },
  { id: 79, name: "2. Bundesliga", country: "Germany", flag: "DE" },
  { id: 40, name: "Championship", country: "England", flag: "GB" },
  { id: 141, name: "La Liga 2", country: "Spain", flag: "ES" },
  { id: 62, name: "Ligue 2", country: "France", flag: "FR" },
];

// Position categories for filtering
export const POSITIONS = [
  "Goalkeeper",
  "Centre-Back",
  "Left-Back",
  "Right-Back",
  "Defensive Midfield",
  "Central Midfield",
  "Attacking Midfield",
  "Left Winger",
  "Right Winger",
  "Centre-Forward",
];
