// Sample Georgian players for fallback/demo mode
// These are real Georgian footballers for realistic demo experience

export const SAMPLE_PLAYERS = [
  {
    id: "sample-player-1",
    name: "Giorgi Kochorashvili",
    age: 25,
    primary_position: "Central Midfield",
    secondary_position: "Defensive Midfield",
    nationality: "Georgia",
    current_club: "Levante UD",
    contract_status: "under_contract",
    stats: { appearances: 28, goals: 3, assists: 5, pass_accuracy: 84 },
    video_links: [],
    scouting_notes: "Box-to-box midfielder with strong defensive work rate. Good passing range and composure under pressure. Can play deeper as a holding midfielder.",
    photo_url: null,
    source: "manual",
    cantera_id: null,
    cantera_active: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "sample-player-2",
    name: "Zuriko Davitashvili",
    age: 23,
    primary_position: "Right Winger",
    secondary_position: "Left Winger",
    nationality: "Georgia",
    current_club: "AS Saint-Etienne",
    contract_status: "under_contract",
    stats: { appearances: 32, goals: 12, assists: 4, dribbles_per_game: 3.2 },
    video_links: [],
    scouting_notes: "Explosive winger with pace and direct dribbling. Strong finisher, prefers cutting inside. Already proven in Ligue 1.",
    photo_url: null,
    source: "manual",
    cantera_id: null,
    cantera_active: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "sample-player-3",
    name: "Luka Lochoshvili",
    age: 25,
    primary_position: "Centre-Back",
    secondary_position: "Left-Back",
    nationality: "Georgia",
    current_club: "Cremonese",
    contract_status: "under_contract",
    stats: { appearances: 25, goals: 1, assists: 0, tackles_per_game: 2.8, aerial_duels_won: 68 },
    video_links: [],
    scouting_notes: "Physical, left-footed centre-back. Strong in the air and comfortable with the ball. Can deputize at left-back. Ready for a step up to Serie A.",
    photo_url: null,
    source: "manual",
    cantera_id: null,
    cantera_active: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "sample-player-4",
    name: "Giorgi Tsitaishvili",
    age: 23,
    primary_position: "Attacking Midfield",
    secondary_position: "Right Winger",
    nationality: "Georgia",
    current_club: "Lech Poznan",
    contract_status: "under_contract",
    stats: { appearances: 30, goals: 7, assists: 8, key_passes_per_game: 2.1 },
    video_links: [],
    scouting_notes: "Creative attacking midfielder with excellent vision. Former Dynamo Kyiv academy product. Adapted well to Ekstraklasa, ready for a bigger league.",
    photo_url: null,
    source: "manual",
    cantera_id: null,
    cantera_active: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "sample-player-5",
    name: "Anzor Mekvabishvili",
    age: 27,
    primary_position: "Defensive Midfield",
    secondary_position: "Central Midfield",
    nationality: "Georgia",
    current_club: "Universitatea Craiova",
    contract_status: "expiring",
    stats: { appearances: 26, goals: 2, assists: 3, interceptions_per_game: 2.4 },
    video_links: [],
    scouting_notes: "Disciplined defensive midfielder with good positional awareness. Screen in front of defence, excellent at breaking up play. Contract expiring — available on a free.",
    photo_url: null,
    source: "manual",
    cantera_id: null,
    cantera_active: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
